/**
 * Markdown Export Service
 * Generates copy-paste friendly markdown digests of news articles
 */

import { prisma } from '../lib/prisma.js';

interface ExportOptions {
  revenueOwnerId: string;
  dateFrom?: Date;
  dateTo?: Date;
  priorityFilter?: ('high' | 'medium' | 'low')[];
}

export async function generateNewsDigestMarkdown(options: ExportOptions): Promise<string> {
  const { revenueOwnerId, dateFrom, dateTo, priorityFilter } = options;

  // Fetch revenue owner
  const owner = await prisma.revenueOwner.findUnique({
    where: { id: revenueOwnerId },
  });

  if (!owner) {
    throw new Error('Revenue owner not found');
  }

  // Build date filter
  const defaultDateFrom = new Date();
  defaultDateFrom.setDate(defaultDateFrom.getDate() - 7);

  // Fetch articles for this owner
  const articles = await prisma.newsArticle.findMany({
    where: {
      revenueOwners: { some: { revenueOwnerId } },
      publishedAt: {
        gte: dateFrom || defaultDateFrom,
        lte: dateTo || new Date(),
      },
      ...(priorityFilter && priorityFilter.length > 0 && {
        priority: { in: priorityFilter },
      }),
    },
    include: {
      company: true,
      person: true,
      tag: true,
    },
    orderBy: [
      { priority: 'asc' },
      { publishedAt: 'desc' },
    ],
  });

  const highPriority = articles.filter(a => a.priority === 'high');
  const mediumPriority = articles.filter(a => a.priority === 'medium');
  const lowPriority = articles.filter(a => a.priority === 'low');

  const formatArticle = (article: typeof articles[0]): string => {
    const lines: string[] = [];

    // Headline
    lines.push(`### ${article.headline}`);
    lines.push('');

    // Metadata badges
    const badges = [
      article.company?.name,
      article.tag?.name,
      article.matchType ? `[${article.matchType.toUpperCase()}]` : null,
    ].filter(Boolean);

    if (badges.length > 0) {
      lines.push(`**${badges.join(' | ')}**`);
      lines.push('');
    }

    // Summary
    if (article.summary) {
      lines.push(article.summary);
      lines.push('');
    }

    // Why it matters
    if (article.whyItMatters) {
      lines.push(`> **Why it matters:** ${article.whyItMatters}`);
      lines.push('');
    }

    // Source link
    const pubDate = article.publishedAt
      ? new Date(article.publishedAt).toLocaleDateString()
      : 'Unknown date';

    lines.push(`[Read more](${article.sourceUrl}) | ${article.sourceName || 'Unknown source'} | ${pubDate}`);
    lines.push('');
    lines.push('---');
    lines.push('');

    return lines.join('\n');
  };

  // Build the markdown document
  const sections: string[] = [];

  // Header
  sections.push('# News Intelligence Digest');
  sections.push('');
  sections.push(`**Prepared for:** ${owner.name}`);
  sections.push(`**Generated:** ${new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })}`);
  sections.push('');
  sections.push('---');
  sections.push('');

  // Summary stats
  sections.push('## Summary');
  sections.push('');
  sections.push(`- **Total Articles:** ${articles.length}`);
  sections.push(`- **High Priority:** ${highPriority.length}`);
  sections.push(`- **Medium Priority:** ${mediumPriority.length}`);
  sections.push(`- **Low Priority:** ${lowPriority.length}`);
  sections.push('');
  sections.push('---');
  sections.push('');

  // High priority articles
  if (highPriority.length > 0) {
    sections.push('## High Priority');
    sections.push('');
    sections.push(...highPriority.map(formatArticle));
  }

  // Medium priority articles
  if (mediumPriority.length > 0) {
    sections.push('## Medium Priority');
    sections.push('');
    sections.push(...mediumPriority.map(formatArticle));
  }

  // Low priority articles
  if (lowPriority.length > 0) {
    sections.push('## Low Priority');
    sections.push('');
    sections.push(...lowPriority.map(formatArticle));
  }

  // Footer
  sections.push('---');
  sections.push('');
  sections.push('*Generated by SSA Intelligence*');

  return sections.join('\n');
}
